Removing locking while looking up tablespace using name
While looking up tablespace oid using name, a tuple lock was taken on the
pg_tablespace entry for the tablespace. This lock was to avoid any concurrent
drop for the same tablespace. However, in queries containing a reader and
writer gang, and if temp_tablespaces GUC is enforced to spill to a specific
tablespace, the reader may try to assign a transaction id for taking a lock,
but a transaction id may no tbe assigned yet. This will cause such queries to
fail.

This commit fixes the issue by removing the requirement to acquire a lock while
looking up a tablespace using name.

Dropping a tablespace mandates that the tablespace must be empty, i.e any
tables created in that tablespace must be dropped before proceeding to drop the
tablespace. If any data exists in the tablespace before drop tablespace being
dispatched to segments, the drop tablespace operation will fail. In cases,
where data was created in the tablespace directory after the command was
dispatched, the contents in the tablespace directory are not dropped, as
someone might have created a table in the tablespace being dropped in this
small window, but the entry for pg_tablespace is removed. The user can still
run ALTER commands to move the table to another tablespace.

With the above behavior, and considering the usage of DROP tablespace
not frequent, we don't need to take locks while looking up the
tablespace using name as it restricts other use cases. For instance:

```sql
CREATE TABLE hashagg_spill(col1 numeric, col2 int) DISTRIBUTED BY (col1);
INSERT INTO hashagg_spill SELECT id, 1 FROM generate_series(1,20000) id;
ANALYZE hashagg_spill;
SET temp_tablespaces=pg_default;
SET statement_mem='1000kB';
CREATE TABLE spill_temptblspace (a numeric) DISTRIBUTED BY (a);
INSERT INTO spill_tmptblspace SELECT avg(col2) col2 FROM hashagg_spill GROUP BY col1 HAVING(sum(col1)) < 0;
ERROR: AssignTransactionId() called by Segment Reader process...
```

Also, added tests to validate that the data files in the tablespace are not
removed in the case described above.